baseurl = "https://windsorpolyamory.com"
metaDataFormat = "yaml"
title = "Windsor Polyamory"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Windsor Polyamory Group"
      introSubtitle = "Located in in Windsor, Ontario, Canada. Join our small (but growing!) community. Get answers to questions such as: \"What's Polyamory?\""
      introPhoto = "/flag.png"
      logo = "/flag.png"

    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Events"
        url = "page/events/"
        weight = 3

    [[languages.en.menu.main]]
        name = "Chat on Discord"
        url = "https://discord.com/invite/X82RtZP"
        weight = 4

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2023 - Windsor Polyamory · All rights reserved"
  favicon = "/favicon.ico"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-purple-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = true

[params.homepage.social]
  # Global params common for both languages
  title = "Chat with us!"
  description = "Join us for a chat or follow Windsor Polyamory"
  discord = "https://discord.com/invite/X82RtZP"
  #facebook = "https://www.facebook.com/WindsorPolyamory/"
  #instagram = "https://www.instagram.com/windsorpolyamory"
  #twitter = "https://twitter.com/WindsorPoly"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true